name: CI (Node)
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Show repo layout
        run: |
          pwd
          ls -la
          echo "Tree:"
          ls -R

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run unit tests (no npm)
        run: node tests/run_tests.js

      - name: Run examples (smoke)
        run: node src/run_examples.js
