name: guard-main
on:
  push:
    branches: [ main ]

jobs:
  block-direct-push:
    runs-on: ubuntu-latest
    steps:
      - name: Soft block direct pushes (allow merge commits)
        # If the push is a merge commit from a PR, the message starts with "Merge pull request"
        if: startsWith(github.event.head_commit.message, 'Merge pull request') == false
        run: |
          echo "::error::Direct push to main detected. Please open a PR."
          exit 1

